#        _                                 _           _          ___                     _ _               
#  _ __ | |__  _ __  _ __   __ _  __ _  __| |_ __ ___ (_)_ __    / / |__   __ _ _ __   __| | | ___ _ __ ___ 
# | '_ \| '_ \| '_ \| '_ \ / _` |/ _` |/ _` | '_ ` _ \| | '_ \  / /| '_ \ / _` | '_ \ / _` | |/ _ \ '__/ __|
# | |_) | | | | |_) | |_) | (_| | (_| | (_| | | | | | | | | | |/ / | | | | (_| | | | | (_| | |  __/ |  \__ \
# | .__/|_| |_| .__/| .__/ \__, |\__,_|\__,_|_| |_| |_|_|_| |_/_/  |_| |_|\__,_|_| |_|\__,_|_|\___|_|  |___/
# |_|         |_|   |_|    |___/                                                                            
