#     _                     _             ___                     _ _               
#    / \   _ __   __ _  ___| |__   ___   / / |__   __ _ _ __   __| | | ___ _ __ ___ 
#   / _ \ | '_ \ / _` |/ __| '_ \ / _ \ / /| '_ \ / _` | '_ \ / _` | |/ _ \ '__/ __|
#  / ___ \| |_) | (_| | (__| | | |  __// / | | | | (_| | | | | (_| | |  __/ |  \__ \
# /_/   \_\ .__/ \__,_|\___|_| |_|\___/_/  |_| |_|\__,_|_| |_|\__,_|_|\___|_|  |___/
#         |_|                                                                       
- name: 'Restart Apache'
  when: apache.started == True
  service: name={{ apache.initscript }} state=restarted

