#                        _          __               _         ___            _        
#  _ __ ___  _   _ _ __ (_)_ __    / / __   ___   __| | ___   / / |_ __ _ ___| | _____ 
# | '_ ` _ \| | | | '_ \| | '_ \  / / '_ \ / _ \ / _` |/ _ \ / /| __/ _` / __| |/ / __|
# | | | | | | |_| | | | | | | | |/ /| | | | (_) | (_| |  __// / | || (_| \__ \   <\__ \
# |_| |_| |_|\__,_|_| |_|_|_| |_/_/ |_| |_|\___/ \__,_|\___/_/   \__\__,_|___/_|\_\___/
#                                                                                      
# make-config
- name: make-config | Deploy /etc/munin/munin-node config
  notify: Restart munin-node
  template: >
    src=etc/munin/munin-node.conf.j2
    dest=/etc/munin/munin-node.conf
    backup=yes

- name: make-config | Deploy logrotate.d/munin-node
  template: >
    src=etc/logrotate.d/munin-node.j2
    dest=/etc/logrotate.d/munin-node.j2
    backup=no

- name: make-config | Log directory should be created
  file: >
    path={{ munin.node.logdirectory }}
    mode=0755
    owner=munin
    group=munin
    state=directory

